version: 1
directus: 10.12.1
vendor: postgres
collections:
  - collection: sites
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: sites
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: sort
      translations: null
      unarchive_value: draft
      versioning: false
    schema:
      name: sites
  - collection: sites_directus_users
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: sites_directus_users
      color: null
      display_template: null
      group: null
      hidden: true
      icon: import_export
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: sites_directus_users
fields:
  - collection: sites
    field: id
    type: uuid
    meta:
      collection: sites
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: sites
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: status
    type: string
    meta:
      collection: sites
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            color: var(--theme--primary)
            foreground: var(--theme--primary)
            background: var(--theme--primary-background)
          - text: $t:draft
            value: draft
            color: var(--theme--foreground)
            foreground: var(--theme--foreground)
            background: var(--theme--background-normal)
          - text: $t:archived
            value: archived
            color: var(--theme--warning)
            foreground: var(--theme--warning)
            background: var(--theme--warning-background)
        showAsDot: true
      field: status
      group: null
      hidden: true
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
            color: var(--theme--primary)
          - text: $t:draft
            value: draft
            color: var(--theme--foreground)
          - text: $t:archived
            value: archived
            color: var(--theme--warning)
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: status
      table: sites
      data_type: character varying
      default_value: published
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: sort
    type: integer
    meta:
      collection: sites
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: sort
      table: sites
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: user_created
    type: uuid
    meta:
      collection: sites
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 4
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_created
      table: sites
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: sites
    field: date_created
    type: timestamp
    meta:
      collection: sites
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 5
      special:
        - cast-timestamp
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: sites
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: user_updated
    type: uuid
    meta:
      collection: sites
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 6
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_updated
      table: sites
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: sites
    field: date_updated
    type: timestamp
    meta:
      collection: sites
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 7
      special:
        - cast-timestamp
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: sites
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: access_token
    type: string
    meta:
      collection: sites
      conditions: null
      display: null
      display_options: null
      field: access_token
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: password
        masked: true
      readonly: false
      required: true
      sort: 10
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: access_token
      table: sites
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: repo
    type: string
    meta:
      collection: sites
      conditions: null
      display: null
      display_options: null
      field: repo
      group: null
      hidden: false
      interface: input
      note: null
      options:
        trim: true
      readonly: false
      required: true
      sort: 9
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: repo
      table: sites
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites
    field: collaborators
    type: alias
    meta:
      collection: sites
      conditions: null
      display: null
      display_options: null
      field: collaborators
      group: null
      hidden: false
      interface: list-m2m
      note: null
      options:
        enableCreate: false
      readonly: false
      required: false
      sort: 11
      special:
        - m2m
      translations: null
      validation: null
      validation_message: null
      width: full
  - collection: sites_directus_users
    field: id
    type: integer
    meta:
      collection: sites_directus_users
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: sites_directus_users
      data_type: integer
      default_value: nextval('sites_directus_users_id_seq'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: sites_directus_users
    field: sites_id
    type: uuid
    meta:
      collection: sites_directus_users
      conditions: null
      display: null
      display_options: null
      field: sites_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: sites_id
      table: sites_directus_users
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: sites
      foreign_key_column: id
  - collection: sites_directus_users
    field: directus_users_id
    type: uuid
    meta:
      collection: sites_directus_users
      conditions: null
      display: null
      display_options: null
      field: directus_users_id
      group: null
      hidden: true
      interface: null
      note: null
      options: null
      readonly: false
      required: false
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: directus_users_id
      table: sites_directus_users
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
relations:
  - collection: directus_settings
    field: public_registration_role
    related_collection: directus_roles
    meta: null
    schema:
      table: directus_settings
      column: public_registration_role
      foreign_key_table: directus_roles
      foreign_key_column: id
      constraint_name: directus_settings_public_registration_role_foreign
      on_update: NO ACTION
      on_delete: SET NULL
  - collection: directus_webhooks
    field: migrated_flow
    related_collection: directus_flows
    meta: null
    schema:
      table: directus_webhooks
      column: migrated_flow
      foreign_key_table: directus_flows
      foreign_key_column: id
      constraint_name: directus_webhooks_migrated_flow_foreign
      on_update: NO ACTION
      on_delete: SET NULL
  - collection: sites
    field: user_created
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: sites
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: sites
      column: user_created
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: sites_user_created_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: sites
    field: user_updated
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: sites
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: sites
      column: user_updated
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: sites_user_updated_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: sites_directus_users
    field: directus_users_id
    related_collection: directus_users
    meta:
      junction_field: sites_id
      many_collection: sites_directus_users
      many_field: directus_users_id
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: sites_directus_users
      column: directus_users_id
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: sites_directus_users_directus_users_id_foreign
      on_update: NO ACTION
      on_delete: SET NULL
  - collection: sites_directus_users
    field: sites_id
    related_collection: sites
    meta:
      junction_field: directus_users_id
      many_collection: sites_directus_users
      many_field: sites_id
      one_allowed_collections: null
      one_collection: sites
      one_collection_field: null
      one_deselect_action: nullify
      one_field: collaborators
      sort_field: null
    schema:
      table: sites_directus_users
      column: sites_id
      foreign_key_table: sites
      foreign_key_column: id
      constraint_name: sites_directus_users_sites_id_foreign
      on_update: NO ACTION
      on_delete: SET NULL
